### ISSUE TITLE
Console Spam (And Memory Leak): checking for banned players

### ISSUE THREAD

**Issue by quiquelhappy** [zachduda/ChatFeelings#18]
**Bug Description** (Required)
Console spam (and memory leak) while enabling plugin, checking for banned players

**How to Reproduce:** (If unsure, you may leave this out)
How can we recreate this bug? 
1.  remove player data from ban plugin
2.  start the server

**Console Errors** (If no errors were thrown, you may skip this step)
[console spam](https://pastebin.com/6M1ZrFdG)

**Environment Info**  (Required)
 - Minecraft Server Version: 1.15.2
 - Server Type: Paper Spigot
 - ChatFeelings Version: v4.6.6

**Anything else?**
Adding a counter while starting up for limiting the amount of checks should be fine

**Comment by zachduda** [comment]
So you manually removed Essentials userdata from the folder and then Chatfeelings started this issue?

**Comment by quiquelhappy** [comment]
> So you manually removed Essentials userdata from the folder and then Chatfeelings started this issue? 

Yes

**Comment by zachduda** [comment]
Seems to be a common issue. Looking into a fix. :)

**Comment by zachduda** [comment]
I think this issue has been resolved as of the latest update. Please feel free to reopen this issue should you notice it again! 😊
